---
repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types_or: [python, pyi]
        require_serial: true

      - id: ruff
        name: ruff
        entry: ruff check
        language: system
        types_or: [python, pyi, jupyter]
        args: [--force-exclude]
        require_serial: true

      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: system
        types_or: [python, pyi, jupyter]
        args: [--force-exclude, --check]
        require_serial: true
