# SPDX-FileCopyrightText: (c) TagStudio Contributors
# SPDX-License-Identifier: MIT

# Prettier https://prettier.io/

bracketSameLine = false
bracketSpacing = true
objectWrap = "preserve"
quoteProps = "as-needed"
singleQuote = false

[[overrides]]
files = [".github/**/*.yml", ".github/**/*.yaml"]
[overrides.options]
singleQuote = true
