# autogenerated by qt_wrapper.py do not edit
top_level_module_names = (
    "QtCore",
    "QtGui",
    "QtWidgets",
    "QtMultimedia",
    "QtMultimediaWidgets",
    "QtSvgWidgets",
    "QtUiTools",
    "QtPdf",
    "QtSvg",
)


def __getattr__(name):
    if name in top_level_module_names:
        import importlib

        return importlib.import_module("PySide6." + name)
    raise AttributeError(name)
