# autogenerated by qt_wrapper.py do not edit
name_map = {
    "QIntList": "PySide6.QtPdf",
    "QPdfBookmarkModel": "PySide6.QtPdf",
    "QPdfDocument": "PySide6.QtPdf",
    "QPdfDocumentRenderOptions": "PySide6.QtPdf",
    "QPdfLink": "PySide6.QtPdf",
    "QPdfLinkModel": "PySide6.QtPdf",
    "QPdfPageNavigator": "PySide6.QtPdf",
    "QPdfPageRenderer": "PySide6.QtPdf",
    "QPdfSearchModel": "PySide6.QtPdf",
    "QPdfSelection": "PySide6.QtPdf",
    "QSvgGenerator": "PySide6.QtSvg",
    "QSvgRenderer": "PySide6.QtSvg",
    "QtPdf": "PySide6.QtPdf",
    "QtSvg": "PySide6.QtSvg",
}
module_names = frozenset(("QtPdf", "QtSvg"))
