# autogenerated by qt_wrapper.py do not edit
import PySide6.QtPdf

QIntList = PySide6.QtPdf.QIntList
QPdfBookmarkModel = PySide6.QtPdf.QPdfBookmarkModel
QPdfDocument = PySide6.QtPdf.QPdfDocument
QPdfDocumentRenderOptions = PySide6.QtPdf.QPdfDocumentRenderOptions
QPdfLink = PySide6.QtPdf.QPdfLink
QPdfLinkModel = PySide6.QtPdf.QPdfLinkModel
QPdfPageNavigator = PySide6.QtPdf.QPdfPageNavigator
QPdfPageRenderer = PySide6.QtPdf.QPdfPageRenderer
QPdfSearchModel = PySide6.QtPdf.QPdfSearchModel
QPdfSelection = PySide6.QtPdf.QPdfSelection

import PySide6.QtSvg

QSvgGenerator = PySide6.QtSvg.QSvgGenerator
QSvgRenderer = PySide6.QtSvg.QSvgRenderer
