# autogenerated by qt_wrapper.py do not edit
name_map = {
    "QIntList": "PySide6.QtUiTools",
    "QUiLoader": "PySide6.QtUiTools",
    "QtUiTools": "PySide6.QtUiTools",
    "loadUiType": "PySide6.QtUiTools",
}
module_names = frozenset(("QtUiTools",))
