name: PySide App Test

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install system dependencies
        run: |
          # dont run update, it is slow 
          # sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libxkbcommon-x11-0 \
            x11-utils \
            libyaml-dev \
            libegl1-mesa \
            libxcb-icccm4 \
            libxcb-image0 \
            libxcb-keysyms1 \
            libxcb-randr0 \
            libxcb-render-util0 \
            libxcb-xinerama0 \
            libopengl0 \
            libxcb-cursor0 \
            libpulse0

      - name: Install dependencies
        run: |
          pip install -Ur requirements.txt

      - name: Run TagStudio app and check exit code
        run: |
          xvfb-run --server-args="-screen 0, 1920x1200x24 -ac +extension GLX +render -noreset"  python tagstudio/tag_studio.py --ci -o /tmp/
          exit_code=$?
          if [ $exit_code -eq 0 ]; then
            echo "TagStudio ran successfully"
          else
            echo "TagStudio failed with exit code $exit_code"
            exit 1
          fi
