name: Docker Image - Release

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        platform: [linux/amd64, linux/arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to ensure the tag is available

      - name: Extract Tag Name
        id: extract_tag
        run: |
          TAG_NAME=$(git describe --tags --exact-match || echo "")
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV

      - name: Checkout specific tag
        if: env.TAG_NAME != ''
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TAG_NAME }}  # Checkout the exact tag

      - name: Set up lowercase repo name
        id: vars
        run: echo "REPO_NAME_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1
        with:
          buildkitd-flags: --debug

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.7.0
        with:
          context: ./docker
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/${{ env.REPO_NAME_LOWER }}:${{ env.TAG_NAME }}
            ghcr.io/${{ env.REPO_NAME_LOWER }}:latest
